# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=50, null=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('canonical_name', models.CharField(blank=True, max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('blog_url', models.URLField(blank=True, null=True)),
                ('whatsapp_group_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('photoalbum_urls', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Body',
                'verbose_name_plural': 'Bodies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BodyChildRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='bodies.body')),
                ('parent', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bodies.body')),
            ],
            options={
                'verbose_name': 'Body-Child Relation',
                'verbose_name_plural': 'Body-Child Relations',
                'ordering': ('parent__name',),
            },
        ),
    ]
