# Generated by Django 3.2.25 on 2025-10-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
