# Generated by Django 2.0.2 on 2018-03-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0002_body_events'),
        ('bodies', '0003_auto_20180303_0033'),
    ]

    operations = [
    ]
