# Generated by Django 2.0.2 on 2018-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0009_auto_20180306_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='short_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
