# Generated by Django 2.0.3 on 2018-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0011_body_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='body',
            name='events',
        ),
    ]
