# Generated by Django 2.0.3 on 2018-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0012_remove_body_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
