# Generated by Django 2.0.3 on 2018-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0013_auto_20180329_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ('name',), 'verbose_name': 'Body', 'verbose_name_plural': 'Bodies'},
        ),
        migrations.AlterModelOptions(
            name='bodychildrelation',
            options={'ordering': ('parent__name',), 'verbose_name': 'Body-Child Relation', 'verbose_name_plural': 'Body-Child Relations'},
        ),
    ]
