# Generated by Django 2.0.3 on 2018-04-03 15:10

from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Body = apps.get_model('bodies', 'Body')
    for body in Body.objects.all().iterator():
        temp = "-".join(body.name.lower().split())
        body.str_id = "".join(c for c in temp if c.isalnum() or c == "-")
        body.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0014_auto_20180401_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='str_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.RunPython(set_my_defaults, lambda *args: None),
        migrations.AlterField(
            model_name='body',
            name='str_id',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
