# Generated by Django 2.0.4 on 2018-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0015_body_str_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='str_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
