# Generated by Django 2.0.5 on 2018-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0016_auto_20180404_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='blog_url',
            field=models.URLField(null=True),
        ),
    ]
