# Generated by Django 2.0.5 on 2018-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0017_body_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
