# Generated by Django 2.0.7 on 2018-08-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0019_body_cover_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': 'Body', 'verbose_name_plural': 'Bodies'},
        ),
    ]
