# Generated by Django 2.1 on 2018-09-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0021_auto_20180925_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'ordering': ('name',), 'verbose_name': 'Body', 'verbose_name_plural': 'Bodies'},
        ),
    ]
