# Generated by Django 3.2.25 on 2025-10-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0023_body_canonical_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='photoalbum_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='body',
            name='whatsapp_group_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
