# Generated by Django 3.2.16 on 2026-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0023_body_canonical_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='whatsapp_group_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
