# Generated by Django 3.2.16 on 2026-01-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0024_body_whatsapp_group_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
