# Generated by Django 3.2.25 on 2025-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0024_auto_20251001_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='short_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
