# Generated by Django 3.2.16 on 2026-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0025_body_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='photoalbum_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
