# Generated by Django 3.2.16 on 2026-01-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0026_body_photoalbum_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
