# Generated by Django 4.2.30 on 2026-05-21 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodies', '0027_body_short_name'),
        ('users', '0044_remove_userprofile_followed_communities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendarAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('resobin', 'ResoBin'), ('google', 'Google')], max_length=20)),
                ('external_user_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('syncing', 'Syncing')], default='active', max_length=20)),
                ('access_token_enc', models.TextField(blank=True, null=True)),
                ('refresh_token_enc', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.CharField(blank=True, max_length=500)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'calendarhub_external_account',
            },
        ),
        migrations.CreateModel(
            name='SharedCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(max_length=7)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'db_table': 'calendarhub_shared_calendar',
            },
        ),
        migrations.CreateModel(
            name='ExternalCalendarSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_token', models.CharField(blank=True, max_length=1000)),
                ('page_token', models.CharField(blank=True, max_length=1000)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('cursor_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='calendarhub.externalcalendaraccount')),
            ],
            options={
                'db_table': 'calendarhub_sync_state',
            },
        ),
        migrations.CreateModel(
            name='ExternalCalendarEventCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(choices=[('resobin', 'ResoBin'), ('google', 'Google')], max_length=20)),
                ('external_event_id', models.CharField(max_length=255)),
                ('external_calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('subsource', models.CharField(choices=[('class', 'Class'), ('tutorial', 'Tutorial'), ('lab', 'Lab'), ('exam', 'Exam'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', max_length=20)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'calendarhub_event_cache',
            },
        ),
        migrations.CreateModel(
            name='CalendarSourcePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_instiapp_going', models.BooleanField(default=True)),
                ('show_instiapp_followed_bodies', models.BooleanField(default=True)),
                ('show_resobin', models.BooleanField(default=True)),
                ('show_google', models.BooleanField(default=False)),
                ('show_blogs', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preferences', to='users.userprofile')),
            ],
            options={
                'db_table': 'calendarhub_source_preference',
            },
        ),
        migrations.CreateModel(
            name='CalendarBodyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodies.body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_body_preferences', to='users.userprofile')),
            ],
            options={
                'db_table': 'calendarhub_body_preference',
            },
        ),
        migrations.CreateModel(
            name='UserSharedCalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarhub.sharedcalendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'calendarhub_shared_subscription',
                'indexes': [models.Index(fields=['user', 'enabled'], name='calendarhub_user_id_b51659_idx')],
                'unique_together': {('user', 'calendar')},
            },
        ),
        migrations.CreateModel(
            name='SharedCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=500)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarhub.sharedcalendar')),
            ],
            options={
                'db_table': 'calendarhub_shared_event',
                'indexes': [models.Index(fields=['calendar', 'start_time'], name='calendarhub_calenda_c404a0_idx'), models.Index(fields=['calendar', 'is_cancelled'], name='calendarhub_calenda_2f9900_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sharedcalendar',
            index=models.Index(fields=['is_active', 'is_public'], name='calendarhub_is_acti_6743d6_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcalendareventcache',
            index=models.Index(fields=['user', 'provider', 'start_time'], name='idx_cache_user_prov_start'),
        ),
        migrations.AddIndex(
            model_name='externalcalendareventcache',
            index=models.Index(fields=['user', 'provider', 'updated_at'], name='idx_cache_user_prov_updated'),
        ),
        migrations.AddIndex(
            model_name='externalcalendareventcache',
            index=models.Index(fields=['user', 'provider', 'is_cancelled'], name='idx_cache_user_prov_cancel'),
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendareventcache',
            unique_together={('user', 'provider', 'external_event_id', 'external_calendar_id')},
        ),
        migrations.AlterUniqueTogether(
            name='externalcalendaraccount',
            unique_together={('user', 'provider')},
        ),
        migrations.AddIndex(
            model_name='calendarbodypreference',
            index=models.Index(fields=['user', 'enabled'], name='calendarhub_user_id_099d0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarbodypreference',
            unique_together={('user', 'body')},
        ),
    ]
