# Generated by Django 4.2.30 on 2026-06-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0027_body_short_name'),
        ('calendarhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarbodypreference',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bodies.body'),
        ),
    ]
