# Generated by Django 3.2.25 on 2026-07-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarhub', '0002_alter_calendarbodypreference_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsourcepreference',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
