# Generated by Django 3.2.25 on 2026-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarhub', '0003_alter_calendarsourcepreference_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsourcepreference',
            name='show_all_events',
            field=models.BooleanField(default=True),
        ),
    ]
