# Generated by Django 3.2.25 on 2026-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarhub', '0004_calendarsourcepreference_show_all_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsourcepreference',
            name='show_all_events',
            field=models.BooleanField(default=False),
        ),
    ]
