# Generated by Django 2.0.2 on 2018-02-17 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180217_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
