# Generated by Django 2.0.2 on 2018-02-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_usereventstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereventstatus',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
