# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ufr', to='roles.bodyrole')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('roll_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ldap_id', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('department_name', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=200, null=True)),
                ('join_year', models.CharField(blank=True, max_length=5, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=5, null=True)),
                ('hostel', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('show_contact_no', models.BooleanField(default=False)),
                ('fcm_id', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('android_version', models.IntegerField(default=0)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('followed_bodies', models.ManyToManyField(blank=True, related_name='followers', to='bodies.Body')),
                ('former_roles', models.ManyToManyField(blank=True, related_name='former_users', through='users.UserFormerRole', to='roles.BodyRole')),
                ('institute_roles', models.ManyToManyField(blank=True, related_name='users', to='roles.InstituteRole')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='roles.BodyRole')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserTagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('endpoint_hash', models.CharField(max_length=60, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('target', models.CharField(choices=[('roll_no', 'Roll No'), ('department', 'Department'), ('degree', 'Degree'), ('join_year', 'Join Year'), ('graduation_year', 'Graduation Year'), ('hostel', 'Hostel'), ('room', 'Room')], max_length=40)),
                ('regex', models.CharField(max_length=150)),
                ('secondary_target', models.CharField(blank=True, choices=[('roll_no', 'Roll No'), ('department', 'Department'), ('degree', 'Degree'), ('join_year', 'Join Year'), ('graduation_year', 'Graduation Year'), ('hostel', 'Hostel'), ('room', 'Room')], max_length=40, null=True)),
                ('secondary_regex', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.usertagcategory')),
            ],
        ),
        migrations.AddField(
            model_name='userformerrole',
            name='user',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ufr', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['active'], name='users_userp_active_9fb6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['ldap_id'], name='users_userp_ldap_id_1370fe_idx'),
        ),
    ]
