# Generated by Django 2.0.2 on 2018-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_institute_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fcm_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
