# Generated by Django 2.0.2 on 2018-03-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180324_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
