# Generated by Django 2.0.5 on 2018-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180521_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
