# Generated by Django 2.0.5 on 2018-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_degree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='room',
            field=models.TextField(blank=True, default=1, null=True),
        ),
    ]
