# Generated by Django 2.0.5 on 2018-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180523_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
