# Generated by Django 2.1 on 2018-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20181003_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='secondary_regex',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='secondary_target',
            field=models.CharField(blank=True, choices=[('roll_no', 'Roll No'), ('department', 'Department'), ('degree', 'Degree'), ('join_year', 'Join Year'), ('graduation_year', 'Graduation Year'), ('hostel', 'Hostel'), ('room', 'Room'), ('android_version', 'Android Version')], max_length=40, null=True),
        ),
    ]
