# Generated by Django 2.1.5 on 2019-02-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userprofile_show_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='join_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
