# Generated by Django 2.1.5 on 2019-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190222_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.TextField(unique=True),
        ),
    ]
