# Generated by Django 2.1.5 on 2019-03-29 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid

former_roles_cache = None

def get_former_roles(apps, schema_editor):
    global former_roles_cache
    BodyRole = apps.get_model('roles', 'BodyRole')
    former_roles_cache = list(BodyRole.objects.prefetch_related('former_users').all())

def put_former_roles(apps, schema_editor):
    global former_roles_cache
    UserFormerRole = apps.get_model('users', 'UserFormerRole')
    for crole in former_roles_cache:
        for user in crole.former_users.all():
            UserFormerRole.objects.create(role_id=crole.id, user_id=user.id)

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0010_bodyrole_permanent'),
        ('users', '0031_auto_20190222_1732'),
    ]

    operations = [
        migrations.RunPython(get_former_roles, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='UserFormerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ufr', to='roles.BodyRole')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='former_roles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='former_roles',
            field=models.ManyToManyField(blank=True, related_name='former_users', through='users.UserFormerRole', to='roles.BodyRole'),
        ),
        migrations.AddField(
            model_name='userformerrole',
            name='user',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ufr', to='users.UserProfile'),
        ),
        migrations.RunPython(put_former_roles, reverse_code=migrations.RunPython.noop),
    ]
