# Generated by Django 2.2.3 on 2019-07-21 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20190329_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
