# Generated by Django 3.0.8 on 2021-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0023_body_canonical_name'),
        ('users', '0035_auto_20190722_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_bodies',
            field=models.ManyToManyField(blank=True, related_name='blockers', to='bodies.Body'),
        ),
    ]
