# Generated by Django 3.0.8 on 2021-02-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userprofile_blocked_bodies'),
        ('users', '0037_auto_20201101_1943'),
    ]

    operations = [
    ]
