# Generated by Django 3.2.13 on 2022-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0009_community_followers"),
        ("users", "0038_auto_20210606_2237"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followed_communities",
            field=models.ManyToManyField(
                blank=True, related_name="followers_Community", to="community.Community"
            ),
        ),
    ]
