# Generated by Django 3.2.16 on 2023-07-24 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_remove_userprofile_community_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="followed_communities",
        ),
    ]
