# Generated by Django 4.2.30 on 2026-06-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0027_body_short_name'),
        ('users', '0044_remove_userprofile_followed_communities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='bodies.body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'body')},
            },
        ),
    ]
