# Generated by Django 4.2.30 on 2026-06-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='contact_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
