# Generated by Django 4.2.30 on 2026-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_signature_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='role',
        ),
        migrations.AddField(
            model_name='signature',
            name='signature',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
