# Generated by Django 4.2.30 on 2026-06-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0027_body_short_name'),
        ('users', '0047_remove_signature_contact_no_remove_signature_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='bodies.body'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.TextField(max_length=200),
        ),
    ]
