# Generated by Django 4.2.30 on 2026-06-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_signature_body_alter_signature_signature'),
        ('users', '0048_auto_20260622_0145'),
    ]

    operations = [
    ]
