# Generated by Django 4.2.30 on 2026-06-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_merge_20260625_2240'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signature',
            table='signature_model',
        ),
    ]
