# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodies', '0001_initial'),
        ('users', '0001_initial'),
        ('achievements', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=58, null=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('email_subject', models.TextField(default='')),
                ('longdescription', models.TextField(default='')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_rejected', models.BooleanField(default=False)),
                ('venue_room', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=True)),
                ('starting_notified', models.BooleanField(default=False)),
                ('promotion_boost', models.IntegerField(default=0)),
                ('bodies', models.ManyToManyField(blank=True, related_name='events', to='bodies.Body')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='users.userprofile')),
                ('event_interest', models.ManyToManyField(blank=True, related_name='events', to='achievements.Interest')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='UserEventStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('event', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='events.event')),
                ('user', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User-Event Status',
                'verbose_name_plural': 'User-Event Statuses',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_events', through='events.UserEventStatus', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='user_tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='users.UserTag'),
        ),
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='events', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='verification_bodies',
            field=models.ManyToManyField(blank=True, related_name='verEvents', to='bodies.Body'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
    ]
