# Generated by Django 2.0.2 on 2018-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id'
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
