# Generated by Django 2.0.2 on 2018-03-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_followed_bodies'),
        ('events', '0009_auto_20180304_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='locations.Location'),
        ),
    ]
