# Generated by Django 2.0.2 on 2018-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180305_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='events', to='locations.Location'),
        ),
    ]
