# Generated by Django 2.0.4 on 2018-04-03 17:44

from django.db import migrations, models
def set_my_defaults(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all().iterator():
        temp = "-".join(event.name.lower().split())
        temp = "".join(c for c in temp if c.isalnum() or c == "-")
        event.str_id = temp + "-" + str(event.id)[:8]
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20180401_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='str_id',
            field=models.CharField(editable=False, max_length=58, null=True),
        ),
        migrations.RunPython(set_my_defaults, lambda *args: None),
        migrations.AlterField(
            model_name='event',
            name='str_id',
            field=models.CharField(editable=False, max_length=58),
        ),
    ]
