# Generated by Django 2.0.4 on 2018-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_str_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='str_id',
            field=models.CharField(editable=False, max_length=58, null=True),
        ),
    ]
