# Generated by Django 2.1.2 on 2018-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='promotion_boost',
            field=models.IntegerField(default=0),
        ),
    ]
