# Generated by Django 3.1.2 on 2021-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0028_event_promotion_boost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
