# Generated by Django 3.2.10 on 2021-12-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0012_auto_20211201_1642"),
        ("events", "0029_auto_20210530_0055"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_interest",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="events", to="achievements.Interest"
            ),
        ),
    ]
