# Generated by Django 3.2.10 on 2022-01-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0012_auto_20211201_1642"),
        ("events", "0030_event_event_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_interest",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="achievements.Interest"
            ),
        ),
    ]
