# Generated by Django 3.2.16 on 2023-12-12 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0032_auto_20231211_2316"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="email_body",
            new_name="longdescription",
        ),
    ]
