# Generated by Django 3.2.16 on 2025-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20231229_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
