# Generated by Django 3.2.16 on 2025-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_event_email_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_subject',
            field=models.TextField(default=''),
        ),
    ]
