# Generated by Django 3.2.16 on 2025-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_event_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_room',
            field=models.TextField(blank=True, null=True),
        ),
    ]
