# Generated by Django 3.2.16 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0043_event_venue_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.CharField(
                blank=True,
                choices=[("event", "Event"), ("announcement", "Announcement")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
