# Generated by Django 3.2.25 on 2026-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Feedback left by the verifier when rejecting an event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, help_text='Set when a previously rejected event is edited and resubmitted.', null=True),
        ),
    ]
