# Generated by Django 3.2.25 on 2026-08-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20260622_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='resubmitted_at',
        ),
    ]
