# Generated by Django 3.2.25 on 2026-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_eventemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
