# Generated by Django 3.2.16 on 2023-09-12 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messmenu', '0004_messcalevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Tech'), (2, 'Sports'), (3, 'Cultural')])),
            ],
        ),
        migrations.CreateModel(
            name='GC_Hostel_Points',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('gc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcleaderboard.gc')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messmenu.hostel')),
            ],
        ),
    ]
