# Generated by Django 3.2.16 on 2023-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcleaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gc_hostel_points',
            name='participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
