# Generated by Django 3.2.10 on 2021-12-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlumniUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ldap", models.CharField(max_length=30)),
                ("keyStored", models.CharField(blank=True, max_length=6, null=True)),
                ("timeLoginRequest", models.DateTimeField()),
            ],
        ),
    ]
