# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_url', models.URLField(null=True)),
                ('notify', models.BooleanField(default=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodies.body')),
            ],
            options={
                'verbose_name': 'News Entry',
                'verbose_name_plural': 'News Entries',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='UserNewsReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.IntegerField(default=0)),
                ('news', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='unr', to='news.newsentry')),
                ('user', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='unr', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User-News Reaction',
                'verbose_name_plural': 'User-News Reactions',
            },
        ),
        migrations.AddField(
            model_name='newsentry',
            name='reacted_by',
            field=models.ManyToManyField(blank=True, related_name='news_reactions', through='news.UserNewsReaction', to='users.UserProfile'),
        ),
        migrations.AddIndex(
            model_name='newsentry',
            index=models.Index(fields=['guid'], name='news_newsen_guid_2db5a2_idx'),
        ),
    ]
