# Generated by Django 2.0.5 on 2018-05-25 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0016_auto_20180404_2222'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('blog_url', models.URLField(null=True)),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bodies.Body')),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
            },
        ),
    ]
