# Generated by Django 2.0.5 on 2018-05-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newssource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssource',
            name='body',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
    ]
