# Generated by Django 2.0.5 on 2018-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180523_2158'),
        ('news', '0004_usernewsreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='reacted_by',
            field=models.ManyToManyField(blank=True, related_name='news_reactions', through='news.UserNewsReaction', to='users.UserProfile'),
        ),
    ]
