# Generated by Django 2.1.4 on 2019-01-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181001_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
