# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('isSkill', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-time_of_creation',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='bodies.body')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('generic', models.CharField(default='generic', max_length=20)),
                ('secret', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_achievements', to='bodies.body')),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
    ]
