# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
        ('achievements', '0001_initial'),
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredachievement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_achievements', to='events.event'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='bodies.body'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='events.event'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='achievements.offeredachievement'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_verified_by', to='users.userprofile'),
        ),
    ]
