# Generated by Django 2.2.3 on 2019-07-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('-time_of_creation',)},
        ),
    ]
