# Generated by Django 2.2.3 on 2019-07-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_offeredachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='achievements.OfferedAchievement'),
        ),
        migrations.AddField(
            model_name='offeredachievement',
            name='secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
