# Generated by Django 2.2.4 on 2019-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_achievement_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='offeredachievement',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
