# Generated by Django 3.2.16 on 2023-12-11 10:18

from django.db import migrations, models
import django.db.models.deletion
import lostandfound.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_remove_userprofile_followed_communities"),
        ("lostandfound", "0002_auto_20231209_1246"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfound",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_products",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="productfound",
            name="claimed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="productfound",
            name="product_image1",
            field=models.ImageField(upload_to=lostandfound.models.get_image_path),
        ),
        migrations.AlterField(
            model_name="productfound",
            name="product_image2",
            field=models.ImageField(
                blank=True, upload_to=lostandfound.models.get_image_path
            ),
        ),
        migrations.AlterField(
            model_name="productfound",
            name="product_image3",
            field=models.ImageField(
                blank=True, upload_to=lostandfound.models.get_image_path
            ),
        ),
    ]
