# Generated by Django 3.2.16 on 2024-01-01 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lostandfound", "0003_alter_productfound_product_image1"),
        ("lostandfound", "0003_auto_20231211_1548"),
    ]

    operations = []
