# Generated by Django 3.2.16 on 2024-01-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_auto_20231211_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfound',
            name='uploaded_by',
        ),
    ]
