# Generated by Django 3.2.16 on 2024-01-02 16:32

from django.db import migrations, models
import lostandfound.models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0004_merge_20240101_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfound',
            name='product_image1',
            field=models.ImageField(upload_to=lostandfound.models.get_image_path),
        ),
    ]
