# Generated by Django 3.2.16 on 2024-01-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0004_remove_productfound_uploaded_by'),
        ('lostandfound', '0005_alter_productfound_product_image1'),
    ]

    operations = [
    ]
