# Generated by Django 3.2.25 on 2026-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementblogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementcompanythread',
            old_name='stipend',
            new_name='bonus_jaf',
        ),
        migrations.RenameField(
            model_name='placementcompanythread',
            old_name='eligibility',
            new_name='cpi_cutoff',
        ),
        migrations.RenameField(
            model_name='placementextracteddata',
            old_name='stipend',
            new_name='bonus_jaf',
        ),
        migrations.RenameField(
            model_name='placementextracteddata',
            old_name='eligibility',
            new_name='cpi_cutoff',
        ),
        migrations.RenameField(
            model_name='placementextracteddata',
            old_name='reporting_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='placementcompanythread',
            name='bond',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placementcompanythread',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placementextracteddata',
            name='bond',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placementextracteddata',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
