# Generated by Django 3.2.25 on 2026-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementblogs', '0002_auto_20260704_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementextracteddata',
            name='placement_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='placementextracteddata',
            name='shortlisted_rolls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
