# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('location_details', models.TextField(blank=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Deleted', 'Deleted')], default='reported', max_length=30)),
                ('latitude', models.FloatField(blank=True, max_length=8, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=8, null=True)),
                ('location_description', models.TextField(blank=True)),
                ('email_sent_to', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='ComplaintAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Complaint Authority',
                'verbose_name_plural': 'Complaint Authorities',
            },
        ),
        migrations.CreateModel(
            name='ComplaintTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_uri', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Complaint Tag',
                'verbose_name_plural': 'Complaint Tags',
            },
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venter.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Image',
                'verbose_name_plural': 'Complaint Images',
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='users.userprofile')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='venter.complaint')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='authorities',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='venter.ComplaintAuthority'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='venter.ComplaintTag'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='users_up_voted',
            field=models.ManyToManyField(blank=True, related_name='users_up_voted', to='users.UserProfile'),
        ),
    ]
