# Generated by Django 2.0.7 on 2018-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='comments',
        ),
        migrations.AddField(
            model_name='complaints',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='complaints',
            name='users_liked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
