# Generated by Django 2.0.7 on 2018-09-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintmedia',
            options={'verbose_name': 'Complaint Medium', 'verbose_name_plural': 'Complaint Media'},
        ),
    ]
