# Generated by Django 2.0.7 on 2018-08-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0002_auto_20180824_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='venter.tag_uris'),
        ),
    ]
