# Generated by Django 2.0.7 on 2018-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0003_complaints_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
