# Generated by Django 2.0.7 on 2018-09-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0003_auto_20180920_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
