# Generated by Django 2.0.7 on 2018-08-27 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0005_auto_20180827_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 10, 49, 34, 267848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 10, 49, 34, 266851, tzinfo=utc)),
        ),
    ]
