# Generated by Django 2.1.2 on 2018-11-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0005_auto_20181120_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.UserProfile'),
        ),
    ]
