# Generated by Django 2.1.2 on 2018-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0005_auto_20181120_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
