# Generated by Django 2.0.7 on 2018-08-27 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userprofile_former_roles'),
        ('venter', '0006_auto_20180827_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 10, 55, 11, 468221, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='comments',
        ),
        migrations.AddField(
            model_name='complaints',
            name='comments',
            field=models.ManyToManyField(blank=True, to='venter.comment'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 10, 55, 11, 465228, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='complaints',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.UserProfile'),
        ),
    ]
