# Generated by Django 2.1.2 on 2018-11-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0006_complaints_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='authorities',
            field=models.ManyToManyField(related_name='complaints', to='venter.Authorities'),
        ),
    ]
