# Generated by Django 2.1.2 on 2018-11-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0007_auto_20181123_1240'),
        ('venter', '0007_auto_20181126_1625'),
    ]

    operations = [
    ]
