# Generated by Django 2.0.7 on 2018-08-27 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0007_auto_20180827_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='users_liked',
            new_name='users_up_voted',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='up_votes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 10, 58, 1, 937473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 10, 58, 1, 934484, tzinfo=utc)),
        ),
    ]
