# Generated by Django 2.1.2 on 2018-11-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0007_auto_20181126_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='auth_email',
            new_name='authorities',
        ),
    ]
