# Generated by Django 2.0.7 on 2018-08-27 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0008_auto_20180827_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_tag_uris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': "Complaint's tags",
                'verbose_name': "Complaint's tag",
            },
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='users_up_voted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 12, 4, 51, 752556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 27, 12, 4, 51, 750556, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='complaint_tag_uris',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venter.complaints'),
        ),
        migrations.AddField(
            model_name='complaint_tag_uris',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tags', to='venter.tag_uris'),
        ),
    ]
