# Generated by Django 2.1.2 on 2018-12-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20181003_1609'),
        ('venter', '0009_auto_20181129_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='users.UserProfile'),
        ),
    ]
