# Generated by Django 2.1.4 on 2018-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('venter', '0010_complaints_email_sent_to'), ('venter', '0011_remove_complaints_email_status'), ('venter', '0012_auto_20181212_1137'), ('venter', '0013_auto_20181212_1310')]

    dependencies = [
        ('venter', '0009_auto_20181129_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='email_sent_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='email_status',
        ),
    ]
