# Generated by Django 2.1.4 on 2018-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0010_complaints_email_sent_to_squashed_0013_auto_20181212_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='email_sent_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
