# Generated by Django 2.1.3 on 2018-12-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0010_complaints_email_sent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='email_status',
        ),
    ]
