# Generated by Django 2.1.2 on 2019-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0010_auto_20181220_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='location_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='email_sent_to',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='location_description',
            field=models.TextField(blank=True),
        ),
    ]
