# Generated by Django 2.1.3 on 2018-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0011_remove_complaints_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='email_sent_to',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
