# Generated by Django 2.1.3 on 2018-12-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0012_auto_20181212_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='email_sent_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
