# Generated by Django 2.1.5 on 2019-02-07 09:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0028_userprofile_show_contact_no'),
        ('venter', '0012_complaints_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
        migrations.RenameModel(
            old_name='Authorities',
            new_name='ComplaintAuthority',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='ComplaintComment',
        ),
        migrations.RenameModel(
            old_name='ComplaintMedia',
            new_name='ComplaintImage',
        ),
        migrations.RenameModel(
            old_name='TagUris',
            new_name='ComplaintTag',
        ),
        migrations.AlterModelOptions(
            name='complaintauthority',
            options={'verbose_name': 'Complaint Authority', 'verbose_name_plural': 'Complaint Authorities'},
        ),
        migrations.AlterModelOptions(
            name='complaintimage',
            options={'verbose_name': 'Complaint Image', 'verbose_name_plural': 'Complaint Images'},
        ),
        migrations.AlterModelOptions(
            name='complainttag',
            options={'verbose_name': 'Complaint Tag', 'verbose_name_plural': 'Complaint Tags'},
        ),
    ]
