# Generated by Django 2.0.7 on 2018-08-28 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180401_2303'),
        ('venter', '0012_auto_20180828_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_uris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Media URI',
                'verbose_name_plural': 'Media URIs',
            },
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='media',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 7, 26, 16, 211599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 7, 26, 16, 211098, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='media_uris',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venter.complaints'),
        ),
        migrations.AddField(
            model_name='media_uris',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='upload.UploadedImage'),
        ),
    ]
