# Generated by Django 2.0.7 on 2018-08-28 07:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0015_auto_20180828_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='altitude',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 7, 36, 9, 169663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 7, 36, 9, 169663, tzinfo=utc)),
        ),
    ]
