# Generated by Django 2.0.7 on 2018-08-29 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180401_2303'),
        ('users', '0022_userprofile_former_roles'),
        ('venter', '0018_auto_20180828_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_tag_uris',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaint_tag_uris',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='complaints_liked_users',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='complaints_liked_users',
            name='user',
        ),
        migrations.RemoveField(
            model_name='media_uris',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='media_uris',
            name='media',
        ),
        migrations.AddField(
            model_name='complaints',
            name='comments',
            field=models.ManyToManyField(blank=True, to='venter.comment'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, related_name='media', to='upload.UploadedImage'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='venter.tag_uris'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='users_up_voted',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 10, 10, 15, 177029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 10, 10, 15, 174037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('deleted', 'Deleted')], default='reported', max_length=30),
        ),
        migrations.DeleteModel(
            name='complaint_tag_uris',
        ),
        migrations.DeleteModel(
            name='complaints_liked_users',
        ),
        migrations.DeleteModel(
            name='media_uris',
        ),
    ]
