# Generated by Django 2.0.7 on 2018-08-29 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0021_auto_20180829_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 10, 27, 24, 620173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 10, 27, 24, 617186, tzinfo=utc)),
        ),
    ]
