# Generated by Django 2.0.7 on 2018-08-29 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0022_auto_20180829_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='venter.complaints'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 12, 8, 9, 697052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 12, 8, 9, 695069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='users_up_voted',
            field=models.ManyToManyField(blank=True, related_name='users_up_voted', to='users.UserProfile'),
        ),
    ]
