# Generated by Django 2.0.7 on 2018-08-30 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0031_auto_20180830_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 6, 14, 48, 235138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 30, 6, 14, 48, 235138, tzinfo=utc)),
        ),
    ]
