# Generated by Django 2.0.7 on 2018-08-30 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0032_auto_20180830_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='media', to='upload.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
