# Generated by Django 2.0.7 on 2018-08-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venter', '0033_auto_20180830_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.UserProfile'),
        ),
    ]
