# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_url', models.URLField(null=True)),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Placement Blog Entry',
                'verbose_name_plural': 'Placement Blog Entries',
                'ordering': ('-published',),
            },
        ),
        migrations.AddIndex(
            model_name='blogentry',
            index=models.Index(fields=['guid'], name='placements__guid_953b4f_idx'),
        ),
    ]
