# Generated by Django 2.0.3 on 2018-04-01 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementblogentry',
            options={'ordering': ('-published',), 'verbose_name': 'Placement Blog Entry', 'verbose_name_plural': 'Placement Blog Entries'},
        ),
        migrations.AddField(
            model_name='placementblogentry',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
