# Generated by Django 2.0.3 on 2018-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_auto_20180401_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementblogentry',
            name='guid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='placementblogentry',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='placementblogentry',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
