# Generated by Django 2.0.4 on 2018-04-08 10:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_auto_20180401_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_url', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Placement Blog Entry',
                'verbose_name_plural': 'Placement Blog Entries',
                'ordering': ('-published',),
            },
        ),
        migrations.DeleteModel(
            name='PlacementBlogEntry',
        ),
    ]
