# Generated by Django 3.1.2 on 2021-07-16 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0006_blogentry_pin_unpin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogentry",
            old_name="pin_unpin",
            new_name="pinned",
        ),
    ]
