# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodies', '0001_initial'),
        ('users', '0001_initial'),
        ('achievements', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=58, null=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_image', models.URLField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.IntegerField(default=0)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_body', to='bodies.body')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=58, null=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('ignored', models.BooleanField(blank=True, default=False, null=True)),
                ('thread_rank', models.IntegerField(blank=True, default=1, null=True)),
                ('ispoll', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(blank=True, default=False)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.community')),
                ('followed_by', models.ManyToManyField(blank=True, related_name='followedposts', to='users.UserProfile')),
                ('interests', models.ManyToManyField(blank=True, related_name='communitypost_interest', to='achievements.Interest')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityposts', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Community Post',
                'verbose_name_plural': 'Community Posts',
                'ordering': ('-time_of_creation',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('allow_multiple_answers', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='community.communitypost')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='community.poll')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('poll', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CommunityPostUserReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.IntegerField(default=0)),
                ('communitypost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucpr', to='community.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucpr', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Community Post User Reaction',
                'verbose_name_plural': 'Community Post User Reactions',
            },
        ),
        migrations.AddField(
            model_name='communitypost',
            name='reacted_by',
            field=models.ManyToManyField(blank=True, related_name='communitypost_reaction', through='community.CommunityPostUserReaction', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='posts_reported', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='tag_body',
            field=models.ManyToManyField(blank=True, related_name='taggedcommunityposts', to='bodies.Body'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='tag_location',
            field=models.ManyToManyField(blank=True, related_name='taggedcommunityposts', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='tag_user',
            field=models.ManyToManyField(blank=True, related_name='taggedcommunitypost', to='users.UserProfile'),
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'unique_together': {('poll', 'user', 'option')},
            },
        ),
    ]
