# Generated by Django 3.2.13 on 2022-07-02 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_auto_20220703_0229"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="followers_count",
        ),
    ]
