# Generated by Django 3.2.13 on 2022-07-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_remove_community_followers_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="community.community",
            ),
        ),
    ]
