# Generated by Django 3.2.13 on 2022-07-02 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0005_alter_communitypost_community"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communitypost",
            old_name="threadRank",
            new_name="thread_rank",
        ),
    ]
