# Generated by Django 3.2.13 on 2022-07-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0007_auto_20220703_0347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="community.community",
            ),
        ),
    ]
