# Generated by Django 3.2.13 on 2022-07-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0008_alter_communitypost_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="followers",
            field=models.IntegerField(default=0),
        ),
    ]
