# Generated by Django 3.2.10 on 2022-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0011_auto_20220714_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communitypost",
            name="reported",
            field=models.BooleanField(default=False),
        ),
    ]
