# Generated by Django 3.2.13 on 2022-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0013_communitypost_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="thread_rank",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
