# Generated by Django 3.2.13 on 2022-07-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0015_alter_communitypost_thread_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="status",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
