# Generated by Django 3.2.13 on 2022-07-29 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0016_alter_communitypost_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communitypost",
            old_name="hidden",
            new_name="deleted",
        ),
    ]
