# Generated by Django 3.2.13 on 2022-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_remove_userprofile_followed_communities"),
        ("community", "0017_rename_hidden_communitypost_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="communitypost_report",
                through="community.CommunityPost",
                to="users.UserProfile",
            ),
        ),
    ]
