# Generated by Django 3.2.13 on 2022-08-22 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0018_communitypost_reported_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitypost",
            name="reported",
        ),
    ]
