# Generated by Django 3.2.13 on 2022-08-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_remove_userprofile_followed_communities"),
        ("community", "0020_remove_communitypost_reported_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True, related_name="posts_reported", to="users.UserProfile"
            ),
        ),
    ]
