# Generated by Django 3.2.13 on 2022-08-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0021_communitypost_reported_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="reports",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
