# Generated by Django 3.2.13 on 2022-08-27 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0022_communitypost_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitypost",
            name="reports",
        ),
    ]
