# Generated by Django 3.2.13 on 2022-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0023_remove_communitypost_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="ignored",
            field=models.BooleanField(default=False),
        ),
    ]
