# Generated by Django 3.2.14 on 2022-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0022_alter_communitypost_anonymous"),
        ("community", "0025_alter_communitypost_anonymous"),
    ]

    operations = []
