# Generated by Django 3.2.13 on 2022-10-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_remove_userprofile_followed_communities"),
        ("bodies", "0023_body_canonical_name"),
        ("community", "0026_merge_20220830_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_body",
                to="bodies.body",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="community.community",
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communitypost_postedby",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="thread_rank",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="communitypostuserreaction",
            name="communitypost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucpr",
                to="community.communitypost",
            ),
        ),
        migrations.AlterField(
            model_name="communitypostuserreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucpr",
                to="users.userprofile",
            ),
        ),
    ]
