# Generated by Django 3.2.25 on 2025-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0029_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='ispoll',
            field=models.BooleanField(default=False),
        ),
    ]
