# Generated by Django 3.1.2 on 2021-07-18 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('querybot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
