# Generated by Django 3.2.13 on 2022-11-16 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("querybot", "0003_chatbotlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatbotlog",
            options={
                "verbose_name": "ChatBotLog",
                "verbose_name_plural": "ChatBotLogs",
            },
        ),
    ]
