# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=58, null=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('product_image', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='Others', max_length=100, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('warranty', models.BooleanField(blank=True, default=None, null=True)),
                ('packaging', models.BooleanField(blank=True, default=None, null=True)),
                ('condition', models.CharField(blank=True, choices=[('1', '01/10'), ('2', '02/10'), ('3', '03/10'), ('4', '04/10'), ('5', '05/10'), ('6', '06/10'), ('7', '07/10'), ('8', '08/10'), ('9', '09/10'), ('10', '10/10')], max_length=2, null=True)),
                ('action', models.CharField(choices=[('sell', 'Sell'), ('giveaway', 'Give Away'), ('rent', 'Rent')], default='sell', max_length=10)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.IntegerField(default=100)),
                ('original_price', models.IntegerField(blank=True, null=True)),
                ('negotiable', models.BooleanField(default=True)),
                ('contact_details', models.CharField(max_length=300)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_inactive', models.DateTimeField(blank=True, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='productsfollowed', to='users.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-time_of_creation',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('addressed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyandsell.product')),
                ('reporter', models.ForeignKey(on_delete=models.SET('User_DNE'), to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endtime', models.DateTimeField(auto_created=True, null=True)),
                ('strikes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyandsell.product')),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endtime', models.DateTimeField()),
                ('user', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['time_of_creation'], name='buyandsell__time_of_5c6bcd_idx'),
        ),
    ]
