# Generated by Django 3.1.12 on 2021-12-03 11:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210606_2237'),
        ('buyandsell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-time_of_creation',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_product_followers_+', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='product',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='action',
            field=models.CharField(choices=[('sell', 'Sell'), ('giveaway', 'Give Away'), ('rent', 'Rent')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('1', '01/10'), ('2', '02/10'), ('3', '03/10'), ('4', '04/10'), ('5', '05/10'), ('6', '06/10'), ('7', '07/10'), ('8', '08/10'), ('9', '09/10'), ('10', '10/10')], default='7', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['time_of_creation'], name='buyandsell__time_of_5c6bcd_idx'),
        ),
    ]
