# Generated by Django 3.2.16 on 2023-04-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buyandsell", "0003_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limit",
            name="endtime",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buyandsell.category",
            ),
        ),
    ]
