# Generated by Django 3.1.12 on 2021-12-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0003_category_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
