# Generated by Django 3.1.12 on 2021-12-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0005_auto_20211218_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='addressed',
            field=models.BooleanField(default=False),
        ),
    ]
