# Generated by Django 3.2.16 on 2023-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyandsell", "0005_alter_limit_endtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
