# Generated by Django 3.1.12 on 2021-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0006_auto_20211219_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='str_id',
            field=models.CharField(editable=False, max_length=58, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET('Other'), to='buyandsell.category'),
        ),
    ]
