# Generated by Django 3.1.12 on 2021-12-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0007_auto_20211221_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyandsell.category'),
        ),
    ]
