# Generated by Django 3.1.12 on 2021-12-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0008_auto_20211221_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='str_id',
        ),
    ]
