# Generated by Django 3.1.12 on 2021-12-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0009_auto_20211221_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='buyandsell.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='str_id',
            field=models.CharField(editable=False, max_length=58, null=True),
        ),
    ]
