# Generated by Django 3.2.16 on 2026-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0009_auto_20230723_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='time_inactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='Others', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('1', '01/10'), ('2', '02/10'), ('3', '03/10'), ('4', '04/10'), ('5', '05/10'), ('6', '06/10'), ('7', '07/10'), ('8', '08/10'), ('9', '09/10'), ('10', '10/10')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
