# Generated by Django 3.1.12 on 2021-12-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0011_auto_20211221_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
