# Generated by Django 3.1.12 on 2021-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210606_2237'),
        ('buyandsell', '0014_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='user',
        ),
        migrations.AddField(
            model_name='ban',
            name='user',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
    ]
