# Generated by Django 2.0.2 on 2018-03-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_resuable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='resuable',
            new_name='reusable',
        ),
    ]
