# Generated by Django 3.2.25 on 2026-05-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('IAF_OPEN', 'IAF Open'), ('TEST', 'Test'), ('TEST_SHORTLIST', 'Test Shortlist'), ('TEST_UPDATE', 'Test Update'), ('ASSIGNMENT_DETAILS', 'Assignment Details'), ('ASSIGNMENT_SHORTLIST', 'Assignment Shortlist'), ('MANDATORY_FORM', 'Mandatory Form'), ('INTERVIEW_SHORTLIST', 'Interview Shortlist'), ('INTERVIEW_SCHEDULE', 'Interview Schedule'), ('INTERVIEW_UPDATE', 'Interview Update'), ('GD_SCHEDULE', 'GD Schedule'), ('GD_UPDATE', 'GD Update'), ('ROUND2_SHORTLIST', 'Round 2 Shortlist'), ('FINAL_SELECTION', 'Final Selection'), ('OTHER', 'Other')], max_length=30)),
                ('raw_company_name', models.CharField(max_length=200)),
                ('published', models.DateTimeField(db_index=True)),
                ('raw_content', models.TextField()),
                ('link', models.URLField()),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='CompanyThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_slug', models.SlugField()),
                ('first_post_date', models.DateTimeField(db_index=True)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('role', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('eligibility', models.TextField(blank=True)),
                ('iaf_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-first_post_date'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=10)),
                ('role', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('eligibility', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('shortlisted_rolls', models.JSONField(blank=True, default=list)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('reporting_time', models.CharField(blank=True, max_length=50)),
                ('interview_slots', models.JSONField(blank=True, default=list)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted', to='internship.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='internship.companythread'),
        ),
    ]
