# Generated by Django 3.2.25 on 2026-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_companythread_id_alter_extracteddata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='interview_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='shortlisted_rolls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
