# Generated by Django 3.2.25 on 2026-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20260712_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companythread',
            name='company_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
