# Generated by Django 2.0.2 on 2018-03-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180221_1718'),
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='events',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
