# Generated by Django 4.2.30 on 2026-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Title Here', max_length=100, verbose_name='Alert Title')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('long_description', models.TextField(blank=True, verbose_name='About')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='image link')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='call to action link')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this popup is currently being served to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pop-up Notification',
                'verbose_name_plural': 'Pop-up Notifications',
                'db_table': 'pop_up',
                'ordering': ['-created_at'],
            },
        ),
    ]
