# Generated by Django 4.2.30 on 2026-06-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_signature_table'),
        ('popup_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='heading',
            field=models.CharField(blank=True, default='Title', max_length=100, verbose_name='Alert Title'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='links',
            field=models.JSONField(blank=True, default=list, verbose_name='Add links'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='short description'),
        ),
        migrations.CreateModel(
            name='UserPopUpRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup_notification.popup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'popup_notification_read_status',
                'unique_together': {('user', 'popup')},
            },
        ),
    ]
