# Generated by Django 3.2.25 on 2026-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_notification', '0002_alter_popup_heading_alter_popup_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Add links'),
        ),
    ]
