# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to=upload.models.get_image_path)),
                ('claimant_id', models.UUIDField(null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ('-time_of_creation',),
            },
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['is_claimed'], name='upload_uplo_is_clai_8be643_idx'),
        ),
    ]
