# Generated by Django 2.0.2 on 2018-03-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='picture',
            field=models.ImageField(upload_to='.'),
        ),
    ]
