# Generated by Django 2.0.3 on 2018-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180317_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ('-time_of_creation',), 'verbose_name': 'Uploaded Image', 'verbose_name_plural': 'Uploaded Images'},
        ),
    ]
