# Generated by Django 2.1 on 2018-09-28 14:18

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180401_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='picture',
            field=models.ImageField(upload_to=upload.models.get_image_path),
        ),
    ]
