# Generated by Django 3.2.25 on 2025-10-01 18:47

from django.db import migrations, models
import django.db.models.deletion
import upload.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_userprofile_followed_communities'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('upload', '0005_auto_20190131_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=upload.models.get_file_path)),
                ('claimant_id', models.UUIDField(null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ('-time_of_creation',),
            },
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['is_claimed'], name='upload_uplo_is_clai_10f52b_idx'),
        ),
    ]
