# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('permissions', multiselectfield.db.fields.MultiSelectField(choices=[('AddB', 'Add Body'), ('DelB', 'Delete Body'), ('BodyChild', 'Modify Body-Child Relations'), ('Location', 'Full control over locations'), ('Role', 'Modify Institute Roles'), ('RoleB', 'Modify roles for any body')], max_length=39)),
            ],
            options={
                'verbose_name': 'Institute Role',
                'verbose_name_plural': 'Institute Roles',
            },
        ),
        migrations.CreateModel(
            name='BodyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('inheritable', models.BooleanField(default=False)),
                ('permissions', multiselectfield.db.fields.MultiSelectField(choices=[('AddE', 'Add Event'), ('UpdE', 'Update Event'), ('DelE', 'Delete Event'), ('VerE', 'Verify Event'), ('UpdB', 'Update Body'), ('Role', 'Modify Roles'), ('VerA', 'Verify Achievements'), ('AppP', 'Moderate Post'), ('ModC', 'Moderate Comment')], max_length=44)),
                ('priority', models.IntegerField(default=0)),
                ('official_post', models.BooleanField(default=True)),
                ('permanent', models.BooleanField(default=False)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='bodies.body')),
            ],
            options={
                'verbose_name': 'Body Role',
                'verbose_name_plural': 'Body Roles',
                'ordering': ('body__name', 'priority'),
            },
        ),
    ]
