# Generated by Django 2.0.2 on 2018-03-20 17:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20180319_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituterole',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AddB', 'Add Body'), ('DelB', 'Delete Body'), ('BodyChild', 'Modify Body-Child Relations'), ('Location', 'Full control over locations'), ('Role', 'Modify Institute Roles'), ('RoleB', 'Modify roles for any body')], max_length=39),
        ),
    ]
