# Generated by Django 2.0.3 on 2018-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_instituterole_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyrole',
            options={'ordering': ('body__name',), 'verbose_name': 'Body Role', 'verbose_name_plural': 'Body Roles'},
        ),
    ]
