# Generated by Django 3.2.13 on 2022-07-16 08:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0015_alter_bodyrole_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodyrole",
            name="permissions",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("AddE", "Add Event"),
                    ("UpdE", "Update Event"),
                    ("DelE", "Delete Event"),
                    ("UpdB", "Update Body"),
                    ("Role", "Modify Roles"),
                    ("VerA", "Verify Achievements"),
                    ("AppP", "Approve Post"),
                    ("DelP", "Delete Post"),
                    ("FeaP", "Feature Post"),
                    ("ModC", "Moderate Comment"),
                ],
                max_length=49,
            ),
        ),
    ]
