# Generated by Django 3.2.16 on 2023-12-11 17:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0021_delete_communityrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodyrole",
            name="permissions",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("AddE", "Add Event"),
                    ("UpdE", "Update Event"),
                    ("DelE", "Delete Event"),
                    ("VerE", "Verify Event"),
                    ("UpdB", "Update Body"),
                    ("Role", "Modify Roles"),
                    ("VerA", "Verify Achievements"),
                    ("AppP", "Moderate Post"),
                    ("ModC", "Moderate Comment"),
                ],
                max_length=44,
            ),
        ),
    ]
