# Generated by Django 3.2.16 on 2023-12-16 12:02

from django.db import migrations
import multiselectfield.db.fields


def migrate_AppP_role_to_ModC_role(apps, schema_editor):
    BodyRole = apps.get_model("roles", "BodyRole")

    for obj in BodyRole.objects.filter(permissions__contains="AppP"):
        obj.permissions.remove("AppP")
        if "ModC" not in obj.permissions:
            obj.permissions.append("ModC")
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0021_delete_communityrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodyrole",
            name="permissions",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("AddE", "Add Event"),
                    ("UpdE", "Update Event"),
                    ("DelE", "Delete Event"),
                    ("UpdB", "Update Body"),
                    ("Role", "Modify Roles"),
                    ("VerA", "Verify Achievements"),
                    ("ModC", "Moderate Community"),
                ],
                max_length=34,
            ),
        ),
        migrations.RunPython(migrate_AppP_role_to_ModC_role),
    ]
