# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('IDF', 'Unappropriate Comment'), ('Buy&Sell', 'Unappropriate Activity in Buy and Sell'), ('Graduated ', 'Passed out from Institute'), ('InstiBan', 'Banned by Insittute Authority')], max_length=30)),
                ('detailed_reason', models.TextField(blank=True)),
                ('duration_of_ban', models.CharField(choices=[('1 month', 'One Month'), ('3 months', 'Three Months'), ('6 months', 'Six Months'), ('12 months', 'Twelve Months'), ('Permanent', 'Permanent')], max_length=20)),
                ('banned_user_ldapid', models.CharField(blank=True, max_length=20, null=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_by', to='users.userprofile')),
                ('banned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_user', to='users.userprofile')),
            ],
        ),
    ]
