# Generated by Django 3.2.16 on 2023-10-10 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_remove_userprofile_followed_communities"),
        ("bans", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SSOBans",
            new_name="SSOBan",
        ),
    ]
