# Generated by Django 3.2.16 on 2023-10-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_remove_userprofile_followed_communities"),
        ("bans", "0003_alter_ssoban_banned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssoban",
            name="banned_user_ldapid",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ssoban",
            name="banned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banned_user",
                to="users.userprofile",
            ),
        ),
    ]
