# Generated by Django 3.2.16 on 2025-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=100, null=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('pixel_x', models.IntegerField(blank=True, null=True)),
                ('pixel_y', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reusable', models.BooleanField(default=False)),
                ('connected_locs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocationLocationDistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.FloatField(default=100000000)),
                ('location1', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='lld1', to='locations.location')),
                ('location2', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='lld2', to='locations.location')),
            ],
            options={
                'verbose_name': 'Location-Location Distance',
                'verbose_name_plural': 'Location-Location Distances',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='adjacent_locs',
            field=models.ManyToManyField(blank=True, related_name='adjacent_loc', through='locations.LocationLocationDistance', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['reusable'], name='locations_l_reusabl_2954ea_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['reusable', 'group_id'], name='locations_l_reusabl_fc1a6b_idx'),
        ),
    ]
