# Generated by Django 2.0.3 on 2018-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20180320_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
