# Generated by Django 2.1.5 on 2019-02-05 22:37

from django.db import migrations, models
def set_my_defaults(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    for location in Location.objects.all().iterator():
        if not location.short_name:
            continue
        temp = "-".join(location.short_name.lower().split())
        location.str_id = "".join(c for c in temp if c.isalnum() or c == "-")
        location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20181001_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='str_id',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.RunPython(set_my_defaults, lambda *args: None),
    ]
