# Generated by Django 2.0.5 on 2018-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='hostel',
            name='mess_gsheet',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='short_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
