# Generated by Django 2.0.5 on 2018-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmenu', '0002_auto_20180618_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='long_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
