# Generated by Django 2.0.2 on 2018-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180218_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ldap_uid',
        ),
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gcm_id',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.URLField(null=True),
        ),
    ]
