# Generated by Django 2.0.2 on 2018-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180218_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gcm_id',
            field=models.IntegerField(null=True),
        ),
    ]
